apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres'
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: test-db
            - name: POSTGRES_USER
              value: test
            - name: POSTGRES_PASSWORD
              value: test
          readinessProbe:
            exec:
              command: [ "psql", "-w", "--username=test", "--dbname=test-db", "-c", "SELECT 1" ]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command: [ "pg_isready", "--username=test", "--dbname=test-db", "--host=127.0.0.1", "--port=5432" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
  selector:
    matchLabels:
      app: postgres
