apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: wiremock
spec:
  selector:
    app: wiremock
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: wiremock
  labels:
    app: wiremock
spec:
  replicas: 1
  template:
    metadata:
      name: wiremock
      labels:
        app: wiremock
    spec:
      containers:
        - name: wiremock
          image: 'wiremock/wiremock'
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: wiremock
