apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: internal
    - port: 9092
      targetPort: 9093
      name: external
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  template:
    metadata:
      name: kafka
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      containers:
        - name: kafka
          image: 'lensesio/fast-data-dev'
          imagePullPolicy: IfNotPresent
          env:
            - name: RUNTESTS
              value: "0"
            - name: SAMPLEDATA
              value: "0"
            - name: RUNNING_SAMPLEDATA
              value: "0"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'kafka:2181'
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: 'INTERNAL'
            - name: KAFKA_LISTENERS
              value: 'INTERNAL://:9092,EXTERNAL://:9092'
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 'INTERNAL://kafka:9092,EXTERNAL://localhost:9093'
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      restartPolicy: Always
  selector:
    matchLabels:
      app: kafka
