apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: schema-registry
spec:
  selector:
    app: schema-registry
  ports:
    - port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: schema-registry
  labels:
    app: schema-registry
spec:
  replicas: 1
  template:
    metadata:
      name: schema-registry
      labels:
        app: schema-registry
    spec:
      enableServiceLinks: false
      containers:
        - name: schema-registry
          image: 'confluentinc/cp-schema-registry:7.4.0'
          imagePullPolicy: IfNotPresent
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: 'PLAINTEXT://kafka:9092'
            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: 'PLAINTEXT'
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: 'schema-registry'
            - name: SCHEMA_REGISTRY_LISTENERS
              value: 'http://schema-registry:8085'
            - name: SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL
              value: 'http'
            - name: SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL
              value: 'INFO'
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
              value: '_schemas'
      restartPolicy: Always
  selector:
    matchLabels:
      app: schema-registry
