apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      name: zookeeper
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: 'confluentinc/cp-zookeeper:7.4.0'
          imagePullPolicy: IfNotPresent
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: '2181'
            - name: ZOOKEEPER_TICK_TIME
              value: '2000'
      restartPolicy: Always
  selector:
    matchLabels:
      app: zookeeper
