apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 32306
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_ROOT_USERNAME
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: toor
          readinessProbe:
            exec:
              command: [ "mysql", "--user=root", "--password=toor", "-h", "127.0.0.1", "-e", "SELECT 1" ]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command: [ "mysqladmin", "--user=root", "--password=toor", "ping" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
  selector:
    matchLabels:
      app: mysql
