spring:
  profiles:
    active: dev

jarvis:
  runner:
    kubernetes:
      context: 'test'
      base-path: 'k8s'
    docker-compose:
      context: 'test'
  services:
    mysql:
      connection:
        username: 'root'
        password: 'toor'
        url: 'jdbc:mysql://mysql:3306/test'
      deployment:
        paths:
          - 'mysql.yaml'
        env:
          name: 'mysql'
    redis:
      connection:
        host: 'localhost'
        port: 6379
      deployment:
        paths:
          - 'redis.yaml'
        env:
          name: 'redis'
    kafka:
      connection:
        bootstrap-servers: 'kafka:9092'
        properties:
          schema.registry.url: 'http://kafka:8081'
        producer:
          client-id: 'jarvis'
      deployment:
        paths:
          - 'kafka.yaml'
        env:
          name: 'kafka'
---
spring:
  config:
    activate:
      on-profile: dev

jarvis:
  services:
    mysql:
      connection:
        url: 'jdbc:mysql://localhost:32306/test'
    redis:
      connection:
        host: 'localhost'
        port: 32379
