jarvis:
  runner:
    kubernetes:
      context: 'test'
    docker-compose:
      context: 'test'
  services:
    mysql:
      username: root
      password: toor
      url: 'jdbc:mysql://localhost:3306/test'
    redis:
      host: localhost
      port: 6379
