apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 32379
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command: [ "redis-cli", "-h", "127.0.0.1", "-p", "6379", "ping" ]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command: [ "redis-cli", "-h", "127.0.0.1", "-p", "6379", "ping" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
  selector:
    matchLabels:
      app: redis
