apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: bootstrap-server
      port: 9092
      targetPort: 9092
    - name: schema-registry
      port: 8081
      targetPort: 8081
    - name: web-server
      port: 3030
      targetPort: 3030
    - name: rest-proxy
      port: 8082
      targetPort: 8082
    - name: kafka-connect
      port: 8083
      targetPort: 8083
    - name: zookeeper
      port: 2181
      targetPort: 2181
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  template:
    metadata:
      name: kafka
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: lensesio/fast-data-dev:2.3.0
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: kafka:2181
          ports:
            - name: server
              containerPort: 9092
            - name: schema
              containerPort: 8081
            - name: web
              containerPort: 3030
            - name: rest-proxy
              containerPort: 8082
            - name: kafka-connect
              containerPort: 8083
            - name: zookeeper
              containerPort: 2181
      restartPolicy: Always
  selector:
    matchLabels:
      app: kafka
